### ISSUE TITLE
packages: ca-certificates-java conflicts

### ISSUE THREAD

**Issue by mockturtl** [linuxmint/lmde6-beta#14]
Is it possible for faye to use `ca-certificates-java: 20230620~deb12u1` from `bookworm-updates`? 

Since it's a dependency of `openjdk-*-jre-headless`, upgrading to version `20230710` will force my JDK(s) to install from sid.

I worry this might lead to downstream compatibility issues with third party Java stuff.

Thanks! :green_heart: 

https://tracker.debian.org/pkg/ca-certificates-java

**Comment by clefebvre** [comment]
hi @mockturtl,

Can you explain the issue you're mentioning? the headless package has a satisfied dependency.. what's going on exactly? What do you mean by forcing your JDK to install from sid?

When working on LMDE we faced a recursive dependency issue when building packages in docker. We found out it was fixed in later versions of ca-certificates so we backported the sid version. This was done on July 10th.

Looking at this https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1911731.html, it seems this fixes the very same issue. I see it's been added to Bookworm on August 7th.

I'd be happy to remove 20230710 from our repositories if we no longer need it. I'd love to understand the issue with JDKs/sid though.

**Comment by mockturtl** [comment]
Ok, I think I see my problem.  I use Google Cloud SDK, where the `google-cloud-cli-firestore-emulator` package has a `Depends: openjdk-8-jdk | openjdk-11-jdk`.

Apparently Java 11 is [end-of-life soon](https://endoflife.date/java), so I guess it was removed from bookworm for hygiene.  I should see whether gcloud has a plan to migrate to Java 17. :smile: 

```
$ sudo apt install ca-certificates-java

The following packages will be REMOVED:  
  openjdk-11-jre-headless{a} 
The following packages will be upgraded:
  ca-certificates-java 
1 packages upgraded, 0 newly installed, 1 to remove and 18 not upgraded.
Need to get 11.8 kB of archives. After unpacking 171 MB will be freed.
The following packages have unmet dependencies:
 openjdk-11-jre : Depends: openjdk-11-jre-headless (= 11.0.18+10-1~deb11u1) but it is not going to be installed
 openjdk-11-jdk-headless : Depends: openjdk-11-jre-headless (= 11.0.18+10-1~deb11u1) but it is not going to be installed

The following actions will resolve these dependencies:

     Upgrade the following packages:                                                   
1)     openjdk-11-jdk [11.0.18+10-1~deb11u1 (now) -> 11.0.21~4ea-1 (unstable)]         
2)     openjdk-11-jdk-headless [11.0.18+10-1~deb11u1 (now) -> 11.0.21~4ea-1 (unstable)]
3)     openjdk-11-jre [11.0.18+10-1~deb11u1 (now) -> 11.0.21~4ea-1 (unstable)]         
4)     openjdk-11-jre-headless [11.0.18+10-1~deb11u1 (now) -> 11.0.21~4ea-1 (unstable)]
```

```
$ apt-cache show ca-certificates-java

Package: ca-certificates-java
Version: 20230710
Architecture: all
Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Installed-Size: 43
Depends: ca-certificates (>= 20210120)
Breaks: openjdk-11-jre-headless (<< 11.0.19+7~1~), openjdk-17-jre-headless (<< 17.0.8~6-3~), openjdk-18-jre-headless (<< 18.0.2+9-2ubuntu1~), openjdk-19-jre-headless (<< 19.0.2+7-0ubuntu4~), openjdk-20-jre-headless (<< 20.0.1+9~1~), openjdk-21-jre-headless (<< 21~9ea-1~), openjdk-8-jre-headless (<< 8u382~b04-2~)
...
```

**Comment by clefebvre** [comment]
Bookworm has JDK 17.

**Comment by clefebvre** [comment]
Anyhow, it looks like Debian either is or has taken care of the original issue, so we no longer need to have our own version of ca-certificates-java. I removed it from the repositories.
