### ISSUE TITLE
PIX Application shuts the window and returns to the lock screen

### ISSUE THREAD

**Issue by kangal3632** [linuxmint/lmde6-beta#24]
I am running LMDE 6 on Gnome boxes which us running on LMDE 5.  Both LMDE 5 and 5 are uptodate.  

Issue: When I click on the PIX app to open it, the screen goes blank and I am returned to the sign-in screen

**Comment by anaximeno** [comment]
I can't reproduce this. Can you try running pix from the terminal? If something strange gets printed there just put it here.

**Comment by kangal3632** [comment]
I ran PIX from the terminal and got the same error.  I imported a jpg and selected PIX as the viewer and I was returned to the sign-in window.  There is no information in the crash reports.  I will download another copy of LMDE-6 beta and set up a new VM and let you know if I have the same problem.

**Comment by kangal3632** [comment]
I downloaded another copy of LMDE-6 Beta and installed it in Gnome Boxes.  PIX is working fine and I am not having any other issues.  I apologize for the extra, unnecessary work.

**Comment by kangal3632** [comment]
I have an update: PIX worked fine on the live demo and after I installed LMDE-6 Beta in Boxes.  After I installed the multimedia codecs, attempts to open PIX took me back to the sign-in screen

**Comment by kangal3632** [comment]
https://github.com/linuxmint/lmde6-beta/assets/100831976/941e69a5-78ca-4b15-844d-b13fc004915f

**Comment by kangal3632** [comment]
https://github.com/linuxmint/lmde6-beta/assets/100831976/d9e23fb8-d339-429f-9012-10d8f0497d26

**Comment by DigiBC** [comment]
I can confirm the same behaviour running LMDE 6 Beta from the ISO file on VMware Workstation 17 Pro (17.0.2), with no difference whether PIX is started from the application shortcut or the terminal.

Log details:
```
09:29:17 at-spi2-registr: X connection to :0 broken (explicit kill or server shutdown).
09:29:17 systemd: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
09:29:17 systemd: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
09:29:17 systemd: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Angedestenebres** [comment]
Hey :cat: 

I got the same issue with Virtualbox so I don't think this is due to the software used for tests.
Moreover, it works with the live ISO on Virtualbox:

![VirtualBox_test_17_09_2023_12_14_57](https://github.com/linuxmint/lmde6-beta/assets/21110485/8c5d173a-73b3-49f9-8892-fd3ee16e3a4e)

I also updated my system and hereafter the list of updates done:
![VirtualBox_LMDE 6 beta_17_09_2023_12_19_06](https://github.com/linuxmint/lmde6-beta/assets/21110485/b91f0e04-f539-415a-8a94-f40a0b19f7b3)

**Comment by Angedestenebres** [comment]
OK, I found the root cause!

In fact, this is due to codecs installation. In fact, before updating my system, I installed them via MintReport.
So I tried again a fresh install without codec and applying updates = OK
After that, new test without update and just install codec pack and I got PIX bug = KO

![VirtualBox_LMDE 6 beta no codec_17_09_2023_13_15_53](https://github.com/linuxmint/lmde6-beta/assets/21110485/9fb0a6e7-5c59-4168-a6b0-af168a329aae)

So I think this package breaks something in dependencies. I'm not sure this is linked to the removed package because a lot of new packages are added and some of them interact with PIX according readme from PIX project: https://github.com/linuxmint/pix

**Comment by kangal3632** [comment]
I downloaded GThumb and I am having the same issue - reboots to sign-in screen

**Comment by mtwebster** [comment]
What format files are these? Does it matter?

Is anyone using any sort of accessibility options? (assuming Cinnamon, menu->Accessibility)

Can you check the Crash Reports tab in the System Reports app for any entries related to pix?

**Comment by Angedestenebres** [comment]
Hey @mtwebster :cat: 

I have nothing on my side after reopening the session:


![VirtualBox_LMDE 6 beta_18_09_2023_17_19_45](https://github.com/linuxmint/lmde6-beta/assets/21110485/01daa0d5-8612-4a3c-b3e2-ae3508359f6e)

But as I said [here](https://github.com/linuxmint/lmde6-beta/issues/24#issuecomment-1722455531), this is linked to the installation of multimedia codecs via MintReport.

**Comment by mtwebster** [comment]
Sure, it's linked, but the solution can't be 'don't install the codecs'.

I can't reproduce this, so I need more info.

**Comment by Angedestenebres** [comment]
I agree we can't give that as solution :D

Hovewer that's strange because on my side fresh install (no/with updates) with codecs installation only and it fails everytime. Launching it with command line doesn't help because the session gets closed when I try to open PIX.

About format file, I have no one, I just open PIX from Cinnamon menu and got this bug.

Unfortunately, I don't have more information to provide for the moment but I'll make a fresh install by installing codecs only + opening PIX and check syslog to see if something can help.

**Comment by clefebvre** [comment]
I don't think this is an issue in Pix or gThumb. It looks like a rendering issue which is triggered by a specific codec and the virtualization environment. If you're back to the login screen, we're probably looking at Xorg crashing here.

You should be able to reproduce this with any viewer.

**Comment by clefebvre** [comment]
You can try to install libavcodec59 (instead of libavcodec-extra59). Either of these satisfy dependencies for mint-meta-codecs.

**Comment by Angedestenebres** [comment]
> I don't think this is an issue in Pix or gThumb. It looks like a rendering issue which is triggered by a specific codec and the virtualization environment. If you're back to the login screen, we're probably looking at Xorg crashing here.
> 
> You should be able to reproduce this with any viewer.

Yes, I have the same issue with Shotwell as well.


> You can try to install libavcodec59 (instead of libavcodec-extra59). Either of these satisfy dependencies for mint-meta-codecs.

Tried but still have the issue.

And in attachment a copy of syslog file after installing a new VM. I only opened a first time PIX to be sure it works, installed codecs and launched again PIX (around 18:59:41).

[syslog.txt](https://github.com/linuxmint/lmde6-beta/files/12651611/syslog.txt)

**Comment by clefebvre** [comment]
Try to identify exactly which package, within mint-meta-codecs dependencies, is causing this.

It's not something we'll be able to fix here, it's definitely upstream, but it'd be good to identify it all the same.

**Comment by clefebvre** [comment]
There only are a few: 

![image](https://github.com/linuxmint/lmde6-beta/assets/1138515/1a1adfd8-299c-484a-8208-0174bff5e117)

**Comment by Angedestenebres** [comment]
Hey :cat: 

After checking, I clearly identified to package in cause of that issue on my side.
This is `gstreamer1.0-vaapi`.

Hereafter the detail about my tests.

**Packages provided with the standard LMDE installation (and included in mint-meta-codecs):**

gstreamer1.0-plugins-good
libdvdnav4
libdvdread8

**PIX launching wihtout any issue after the installation of the following packages:**

gstreamer1.0-plugins-bad: Come with following dependencies:   gstreamer1.0-plugins-bad imagemagick-6-common libdca0 libdirectfb-1.7-7 libfaad2 libfftw3-double3 libfluidsynth3 libimath-3-1-29 libinstpatch-1.0-2 libjxr-tools libjxr0 libkate1 liblqr-1-0 liblrdf0 libltc11 libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6 libmjpegutils-2.1-0 libmodplug1 libmpcdec6 libmpeg2encpp-2.1-0 libmplex2-2.1-0 libneon27 libopenexr-3-1-30 libopenh264-7 libopenni2-0 libqrencode4 libsoundtouch1 libspandsp2 libsrtp2-1 libvo-aacenc0 libvo-amrwbenc0 libwildmidi2 libwmflite-0.2-7 libzbar0 timgm6mb-soundfont
no issue after installation

gstreamer1.0-plugins-ugly: Come with following dependencies: liba52-0.7.4 libmpeg2-4 libopencore-amrnb0 libopencore-amrwb0 libsidplay1v5

gstreamer1.0-libav: no issue after installation

libdvdcss2: no issue after installation

cabextract: Come with following dependencies: libmspack0 - no issue after installation

unshield: Come with following dependencies: libunshield0 - no issue after installation

**PIX crashes when I install only this package:**

gstreamer1.0-vaapi

**Comment by clefebvre** [comment]
It looks like it's well known upstream:

https://gitlab.freedesktop.org/xorg/xserver/-/issues/1053
https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1745345

Thanks @Angedestenebres for troubleshooting. This is definitely upstream from us so we'll leave it at that here.

mint-meta-codecs itself is only a meta package, so once you've removed the vaapi package, you don't need it anymore.
