### ISSUE TITLE
mintupdate: install icon isn't symbolic

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/lmde6-beta#32]
![](https://user-images.githubusercontent.com/63073056/269307938-23578250-eba1-4366-acc6-05b459487c6a.png)

I saw in the commit that it should be a symbolic Icon but for some reason it is not being treated as an symbolic icon by the system.

If I am not wrong not all svg image are directly treated as symbolic icons, so it might be something related to the color or configuration of the svg image.

Related to https://github.com/linuxmint/lmde6-beta/issues/7

**Comment by anaximeno** [comment]
Another thing is that the name of the icon used in the commit https://github.com/linuxmint/mintupdate/commit/d019553865089c94b8ff2fe35f3e077be124caea is different than the icon added in the hicolor icons dir. On the main.ui file in the commit the icon referenced is the **mintupdate-action-install-symbolic** and in the icon added is named **mintupdate-action-install** so it might just be fall-backing to the colored icon hence not adapting to the dark/light themes.

**Comment by mtwebster** [comment]
fixed: https://github.com/linuxmint/mintupdate/commit/1883a1e0154029e6697972842cf61c9b6f48c5fb

Thanks

**Comment by Angedestenebres** [comment]
Hello,

Just a little remark about that icon. The change has been done with MintUpdate 6.0.5 but this is not the same icon than LDME 5 (who has the same icon than Mint 21.x).

LMDE 5:
![VirtualBox_LMDE_22_09_2023_11_33_27](https://github.com/linuxmint/lmde6-beta/assets/21110485/5fa100f7-2952-410e-be62-0efde10df4fc)

LMDE 6:
![VirtualBox_LMDE 6 beta 2_22_09_2023_11_35_00](https://github.com/linuxmint/lmde6-beta/assets/21110485/c5f2a1ab-ee5c-4baf-943a-98939c4e521f)

Maybe It will change in Mint 22 too but I notice that because this is not harmonized :)
